.pragma library

// curated emoji set for the launcher's `e ` mode. each row is [glyph, name,
// extra keywords]. search matches name or keywords, so "lol" finds 😂 etc.
// not exhaustive on purpose — the common ones, kept short so it stays fast.
const LIST = [
    ["😀", "grinning face", "smile happy"],
    ["😃", "grinning big eyes", "smile happy"],
    ["😄", "grinning smiling eyes", "smile happy"],
    ["😁", "beaming face", "grin smile"],
    ["😆", "grinning squinting", "laugh haha"],
    ["😅", "grinning sweat", "phew relief laugh"],
    ["🤣", "rolling on floor laughing", "rofl lol haha"],
    ["😂", "face with tears of joy", "lol laugh cry haha"],
    ["🙂", "slightly smiling", "smile"],
    ["🙃", "upside down", "silly sarcasm"],
    ["😉", "winking face", "wink flirt"],
    ["😊", "smiling blushing", "happy warm"],
    ["😇", "smiling halo", "angel innocent"],
    ["🥰", "smiling hearts", "love adore"],
    ["😍", "heart eyes", "love crush"],
    ["🤩", "star struck", "wow amazed"],
    ["😘", "blowing a kiss", "love kiss"],
    ["😗", "kissing face", "kiss"],
    ["😚", "kissing closed eyes", "kiss"],
    ["😋", "savoring food", "yum tasty tongue"],
    ["😛", "tongue out", "silly"],
    ["😜", "winking tongue", "silly joke"],
    ["🤪", "zany face", "silly wild goofy"],
    ["😝", "squinting tongue", "silly"],
    ["🤑", "money mouth", "rich dollar"],
    ["🤗", "hugging face", "hug"],
    ["🤭", "hand over mouth", "oops giggle"],
    ["🤫", "shushing", "quiet shh secret"],
    ["🤔", "thinking face", "hmm think"],
    ["🤐", "zipper mouth", "quiet secret"],
    ["🤨", "raised eyebrow", "suspicious skeptic"],
    ["😐", "neutral face", "meh"],
    ["😑", "expressionless", "blank meh"],
    ["😶", "no mouth", "speechless blank"],
    ["😏", "smirking", "smug flirt"],
    ["😒", "unamused", "meh annoyed"],
    ["🙄", "rolling eyes", "annoyed whatever"],
    ["😬", "grimacing", "awkward eek"],
    ["😮‍💨", "exhaling", "sigh relief"],
    ["🤥", "lying face", "pinocchio liar"],
    ["😌", "relieved face", "calm content"],
    ["😔", "pensive", "sad down"],
    ["😪", "sleepy", "tired"],
    ["🤤", "drooling", "yum"],
    ["😴", "sleeping", "zzz tired"],
    ["😷", "medical mask", "sick"],
    ["🤒", "thermometer face", "sick ill"],
    ["🤕", "head bandage", "hurt injured"],
    ["🤢", "nauseated", "sick gross ew"],
    ["🤮", "vomiting", "sick puke gross"],
    ["🤧", "sneezing", "sick tissue"],
    ["🥵", "hot face", "heat sweat"],
    ["🥶", "cold face", "freezing"],
    ["🥴", "woozy", "drunk dizzy"],
    ["😵", "dizzy face", "knocked out"],
    ["😵‍💫", "spiral eyes", "dizzy confused"],
    ["🤯", "exploding head", "mind blown wow"],
    ["🤠", "cowboy", "hat yeehaw"],
    ["🥳", "partying face", "celebrate party"],
    ["😎", "sunglasses", "cool"],
    ["🤓", "nerd face", "geek glasses"],
    ["🧐", "monocle", "inspect fancy"],
    ["😕", "confused", "unsure"],
    ["😟", "worried", "concerned"],
    ["🙁", "slightly frowning", "sad"],
    ["😮", "open mouth", "wow surprise"],
    ["😯", "hushed", "surprise"],
    ["😲", "astonished", "shocked wow"],
    ["😳", "flushed", "embarrassed blush"],
    ["🥺", "pleading face", "puppy eyes please"],
    ["😦", "frowning open mouth", "sad"],
    ["😨", "fearful", "scared"],
    ["😰", "anxious sweat", "nervous"],
    ["😥", "sad relieved", "phew"],
    ["😢", "crying", "sad tear"],
    ["😭", "loudly crying", "sob bawl sad"],
    ["😱", "screaming fear", "shock scared"],
    ["😖", "confounded", "frustrated"],
    ["😣", "persevering", "struggle"],
    ["😞", "disappointed", "sad"],
    ["😓", "downcast sweat", "sad tired"],
    ["😩", "weary", "tired ugh"],
    ["😫", "tired face", "ugh exhausted"],
    ["🥱", "yawning", "bored tired"],
    ["😤", "steam nose", "frustrated proud"],
    ["😡", "pouting", "angry mad rage"],
    ["😠", "angry", "mad"],
    ["🤬", "cursing", "swear angry"],
    ["😈", "smiling horns", "devil evil mischief"],
    ["👿", "angry horns", "devil imp"],
    ["💀", "skull", "dead death"],
    ["☠️", "skull crossbones", "dead poison"],
    ["💩", "poop", "poo crap"],
    ["🤡", "clown", "creepy"],
    ["👹", "ogre", "monster"],
    ["👻", "ghost", "boo spooky"],
    ["👽", "alien", "ufo"],
    ["🤖", "robot", "bot ai"],
    ["🎃", "jack o lantern", "halloween pumpkin"],
    ["😺", "grinning cat", "smile"],
    ["😸", "grinning cat eyes", "smile"],
    ["😹", "cat tears joy", "laugh"],
    ["😻", "heart eyes cat", "love"],
    ["🙀", "weary cat", "shock"],
    ["😾", "pouting cat", "angry"],
    ["💋", "kiss mark", "lips"],
    ["👋", "waving hand", "hi hello bye wave"],
    ["🤚", "raised back hand", "stop"],
    ["✋", "raised hand", "stop high five"],
    ["🖐️", "hand fingers splayed", "stop"],
    ["👌", "ok hand", "okay perfect"],
    ["🤌", "pinched fingers", "italian chef"],
    ["🤏", "pinch", "small tiny"],
    ["✌️", "victory", "peace two"],
    ["🤞", "crossed fingers", "luck hope"],
    ["🤟", "love you gesture", "ily"],
    ["🤘", "rock on", "horns metal"],
    ["🤙", "call me", "shaka hang loose"],
    ["👈", "point left", "left"],
    ["👉", "point right", "right"],
    ["👆", "point up", "up"],
    ["👇", "point down", "down"],
    ["☝️", "point up single", "one"],
    ["👍", "thumbs up", "yes good like approve"],
    ["👎", "thumbs down", "no bad dislike"],
    ["✊", "raised fist", "power"],
    ["👊", "fist bump", "punch"],
    ["👏", "clapping", "applause bravo"],
    ["🙌", "raising hands", "hooray praise"],
    ["👐", "open hands", "hug"],
    ["🤲", "palms together", "pray please"],
    ["🙏", "folded hands", "pray thanks please"],
    ["✍️", "writing hand", "write"],
    ["💅", "nail polish", "manicure fancy"],
    ["💪", "flexed biceps", "muscle strong gym"],
    ["🧠", "brain", "smart mind"],
    ["👀", "eyes", "look watch"],
    ["👁️", "eye", "look"],
    ["❤️", "red heart", "love"],
    ["🧡", "orange heart", "love"],
    ["💛", "yellow heart", "love"],
    ["💚", "green heart", "love"],
    ["💙", "blue heart", "love"],
    ["💜", "purple heart", "love"],
    ["🖤", "black heart", "love"],
    ["🤍", "white heart", "love"],
    ["🤎", "brown heart", "love"],
    ["💔", "broken heart", "sad breakup"],
    ["❣️", "heart exclamation", "love"],
    ["💕", "two hearts", "love"],
    ["💞", "revolving hearts", "love"],
    ["💓", "beating heart", "love"],
    ["💗", "growing heart", "love"],
    ["💖", "sparkling heart", "love"],
    ["💘", "heart arrow", "cupid love"],
    ["💝", "heart ribbon", "gift love"],
    ["💯", "hundred points", "100 perfect keep it"],
    ["💢", "anger symbol", "mad"],
    ["💥", "collision", "boom explode"],
    ["💫", "dizzy", "stars"],
    ["💦", "sweat droplets", "water splash"],
    ["💨", "dash", "wind fast"],
    ["🔥", "fire", "lit hot flame"],
    ["✨", "sparkles", "shiny clean magic"],
    ["⭐", "star", "favorite"],
    ["🌟", "glowing star", "shine"],
    ["⚡", "lightning", "bolt fast power"],
    ["🌈", "rainbow", "pride"],
    ["☀️", "sun", "sunny"],
    ["🌙", "crescent moon", "night"],
    ["⛅", "sun behind cloud", "weather"],
    ["☁️", "cloud", "weather"],
    ["❄️", "snowflake", "cold snow winter"],
    ["💧", "droplet", "water"],
    ["🌊", "wave", "ocean water"],
    ["🐶", "dog", "puppy"],
    ["🐱", "cat", "kitten"],
    ["🐭", "mouse", ""],
    ["🐹", "hamster", ""],
    ["🐰", "rabbit", "bunny"],
    ["🦊", "fox", ""],
    ["🐻", "bear", ""],
    ["🐼", "panda", ""],
    ["🐨", "koala", ""],
    ["🐯", "tiger", ""],
    ["🦁", "lion", ""],
    ["🐮", "cow", ""],
    ["🐷", "pig", ""],
    ["🐸", "frog", ""],
    ["🐵", "monkey", ""],
    ["🐔", "chicken", ""],
    ["🐧", "penguin", ""],
    ["🐦", "bird", ""],
    ["🦆", "duck", ""],
    ["🦉", "owl", ""],
    ["🐴", "horse", ""],
    ["🦄", "unicorn", ""],
    ["🐝", "bee", "honey"],
    ["🐛", "bug", "worm"],
    ["🦋", "butterfly", ""],
    ["🐌", "snail", "slow"],
    ["🐢", "turtle", "slow"],
    ["🐍", "snake", ""],
    ["🐙", "octopus", ""],
    ["🦀", "crab", ""],
    ["🐳", "whale", ""],
    ["🐬", "dolphin", ""],
    ["🐟", "fish", ""],
    ["🦈", "shark", ""],
    ["🐊", "crocodile", ""],
    ["🐘", "elephant", ""],
    ["🦒", "giraffe", ""],
    ["🐐", "goat", ""],
    ["🐓", "rooster", ""],
    ["🌵", "cactus", "desert"],
    ["🌲", "evergreen tree", "pine"],
    ["🌴", "palm tree", "beach"],
    ["🌷", "tulip", "flower"],
    ["🌹", "rose", "flower love"],
    ["🌻", "sunflower", "flower"],
    ["🌸", "cherry blossom", "flower sakura"],
    ["💐", "bouquet", "flowers"],
    ["🍀", "four leaf clover", "luck"],
    ["🍁", "maple leaf", "autumn fall"],
    ["🍄", "mushroom", ""],
    ["🍎", "apple", "fruit"],
    ["🍏", "green apple", "fruit"],
    ["🍊", "orange", "fruit"],
    ["🍋", "lemon", "fruit sour"],
    ["🍌", "banana", "fruit"],
    ["🍉", "watermelon", "fruit"],
    ["🍇", "grapes", "fruit"],
    ["🍓", "strawberry", "fruit"],
    ["🫐", "blueberries", "fruit"],
    ["🍑", "peach", "fruit butt"],
    ["🍒", "cherries", "fruit"],
    ["🥭", "mango", "fruit"],
    ["🍍", "pineapple", "fruit"],
    ["🥥", "coconut", ""],
    ["🥑", "avocado", ""],
    ["🍅", "tomato", ""],
    ["🌽", "corn", ""],
    ["🌶️", "hot pepper", "spicy chili"],
    ["🥕", "carrot", ""],
    ["🧄", "garlic", ""],
    ["🧅", "onion", ""],
    ["🥔", "potato", ""],
    ["🍞", "bread", ""],
    ["🧀", "cheese", ""],
    ["🥚", "egg", ""],
    ["🍳", "fried egg", "cooking breakfast"],
    ["🥓", "bacon", ""],
    ["🍔", "hamburger", "burger"],
    ["🍟", "fries", "chips"],
    ["🍕", "pizza", ""],
    ["🌭", "hot dog", ""],
    ["🌮", "taco", ""],
    ["🌯", "burrito", ""],
    ["🍜", "ramen", "noodles soup"],
    ["🍣", "sushi", ""],
    ["🍦", "ice cream", "soft serve"],
    ["🍩", "donut", "doughnut"],
    ["🍪", "cookie", ""],
    ["🎂", "birthday cake", "bday"],
    ["🍰", "cake slice", "dessert"],
    ["🍫", "chocolate", ""],
    ["🍬", "candy", "sweet"],
    ["🍭", "lollipop", "candy"],
    ["🍿", "popcorn", "movie"],
    ["☕", "coffee", "hot tea"],
    ["🍵", "tea", ""],
    ["🍺", "beer", "drink"],
    ["🍻", "cheers", "beers drink"],
    ["🍷", "wine", "drink"],
    ["🍸", "cocktail", "martini drink"],
    ["🥂", "champagne clink", "cheers toast"],
    ["🍾", "champagne", "celebrate"],
    ["🚗", "car", "drive"],
    ["🚕", "taxi", ""],
    ["🚙", "suv", "car"],
    ["🚌", "bus", ""],
    ["🏎️", "race car", "fast"],
    ["🚓", "police car", ""],
    ["🚑", "ambulance", ""],
    ["🚒", "fire truck", ""],
    ["🚚", "truck", ""],
    ["🚲", "bike", "bicycle"],
    ["🛵", "scooter", ""],
    ["🏍️", "motorcycle", ""],
    ["✈️", "airplane", "flight travel"],
    ["🚀", "rocket", "launch space ship"],
    ["🛸", "ufo", "alien"],
    ["🚁", "helicopter", ""],
    ["⛵", "sailboat", ""],
    ["🚂", "train", ""],
    ["🚦", "traffic light", ""],
    ["🗺️", "map", "travel"],
    ["🏠", "house", "home"],
    ["🏢", "office building", "work"],
    ["🏥", "hospital", ""],
    ["🏦", "bank", ""],
    ["🏨", "hotel", ""],
    ["🏫", "school", ""],
    ["⛪", "church", ""],
    ["🗽", "statue of liberty", "nyc"],
    ["🗼", "tokyo tower", ""],
    ["🏰", "castle", ""],
    ["⛺", "tent", "camping"],
    ["🌍", "globe europe africa", "earth world"],
    ["🌎", "globe americas", "earth world"],
    ["🌏", "globe asia", "earth world"],
    ["⚽", "soccer ball", "football"],
    ["🏀", "basketball", ""],
    ["🏈", "football", "american"],
    ["⚾", "baseball", ""],
    ["🎾", "tennis", ""],
    ["🏐", "volleyball", ""],
    ["🎱", "8 ball", "pool billiards"],
    ["🏓", "ping pong", "table tennis"],
    ["🏸", "badminton", ""],
    ["🥅", "goal net", ""],
    ["⛳", "golf", ""],
    ["🎣", "fishing", ""],
    ["🥊", "boxing glove", ""],
    ["🎿", "ski", ""],
    ["🎯", "dart", "bullseye target"],
    ["🎮", "game controller", "gaming videogame"],
    ["🕹️", "joystick", "arcade game"],
    ["🎲", "dice", "game roll"],
    ["🎰", "slot machine", "gamble"],
    ["🧩", "puzzle piece", "jigsaw"],
    ["🎨", "artist palette", "art paint"],
    ["🎬", "clapper board", "movie film"],
    ["🎤", "microphone", "sing karaoke"],
    ["🎧", "headphones", "music"],
    ["🎵", "music note", "song"],
    ["🎶", "music notes", "song"],
    ["🎸", "guitar", "music"],
    ["🎹", "piano keyboard", "music"],
    ["🎺", "trumpet", "music"],
    ["🥁", "drum", "music"],
    ["🎻", "violin", "music"],
    ["📱", "mobile phone", "smartphone"],
    ["💻", "laptop", "computer"],
    ["🖥️", "desktop computer", "monitor pc"],
    ["⌨️", "keyboard", ""],
    ["🖱️", "mouse", "computer"],
    ["🖨️", "printer", ""],
    ["💾", "floppy disk", "save"],
    ["💿", "cd disc", ""],
    ["📷", "camera", "photo"],
    ["📸", "camera flash", "photo"],
    ["🎥", "movie camera", "film"],
    ["📺", "television", "tv"],
    ["📻", "radio", ""],
    ["☎️", "telephone", "call"],
    ["🔋", "battery", "power"],
    ["🔌", "plug", "power electric"],
    ["💡", "light bulb", "idea"],
    ["🔦", "flashlight", "torch"],
    ["🕯️", "candle", ""],
    ["💸", "money wings", "cash spend"],
    ["💵", "dollar", "money cash"],
    ["💰", "money bag", "cash rich"],
    ["💳", "credit card", "pay"],
    ["💎", "gem", "diamond"],
    ["⚖️", "balance scale", "justice law"],
    ["🔧", "wrench", "fix tool"],
    ["🔨", "hammer", "tool build"],
    ["🛠️", "hammer wrench", "tools fix"],
    ["⚙️", "gear", "settings cog"],
    ["🧰", "toolbox", "tools"],
    ["🧲", "magnet", ""],
    ["🔫", "water pistol", "gun"],
    ["💣", "bomb", "explode"],
    ["🔪", "knife", "cut"],
    ["🗡️", "dagger", "sword"],
    ["🛡️", "shield", "defense"],
    ["🔑", "key", "lock"],
    ["🔒", "locked", "secure private"],
    ["🔓", "unlocked", "open"],
    ["🔔", "bell", "notification"],
    ["🔕", "bell off", "mute silent"],
    ["📌", "pushpin", "pin"],
    ["📍", "round pin", "location"],
    ["📎", "paperclip", "attach"],
    ["✂️", "scissors", "cut"],
    ["📝", "memo", "note write"],
    ["✏️", "pencil", "write edit"],
    ["🖊️", "pen", "write"],
    ["📁", "folder", "directory"],
    ["📂", "open folder", "directory"],
    ["📅", "calendar", "date"],
    ["📆", "tear calendar", "date"],
    ["📊", "bar chart", "graph stats"],
    ["📈", "chart up", "growth stonks"],
    ["📉", "chart down", "loss decline"],
    ["📖", "open book", "read"],
    ["📚", "books", "read study"],
    ["🔖", "bookmark", "save"],
    ["📰", "newspaper", "news"],
    ["✅", "check mark", "done yes ok tick"],
    ["✔️", "check", "done yes tick"],
    ["☑️", "checkbox checked", "done"],
    ["❌", "cross mark", "no wrong x"],
    ["❎", "cross button", "no"],
    ["➕", "plus", "add"],
    ["➖", "minus", "subtract"],
    ["➗", "divide", ""],
    ["✖️", "multiply", "times"],
    ["♾️", "infinity", "forever"],
    ["❓", "question mark", "help"],
    ["❗", "exclamation", "warning important"],
    ["⚠️", "warning", "caution alert"],
    ["🚫", "prohibited", "no ban"],
    ["✔", "check thin", "done"],
    ["🔴", "red circle", "dot"],
    ["🟠", "orange circle", "dot"],
    ["🟡", "yellow circle", "dot"],
    ["🟢", "green circle", "dot online"],
    ["🔵", "blue circle", "dot"],
    ["🟣", "purple circle", "dot"],
    ["⚫", "black circle", "dot"],
    ["⚪", "white circle", "dot"],
    ["🎉", "party popper", "celebrate tada congrats"],
    ["🎊", "confetti ball", "celebrate party"],
    ["🎈", "balloon", "party"],
    ["🎁", "gift", "present"],
    ["🏆", "trophy", "win award champion"],
    ["🥇", "gold medal", "first win"],
    ["🥈", "silver medal", "second"],
    ["🥉", "bronze medal", "third"],
    ["🎖️", "military medal", "award"],
    ["🏅", "sports medal", "award"],
    ["👑", "crown", "king queen royal"],
    ["💍", "ring", "engagement wedding"],
    ["🕐", "clock", "time"],
    ["⏰", "alarm clock", "wake time"],
    ["⏳", "hourglass", "time wait loading"],
    ["⌛", "hourglass done", "time"],
    ["⏱️", "stopwatch", "timer"],
    ["🧭", "compass", "direction navigate"],
    ["🌡️", "thermometer", "temperature"],
]

function search(q, limit) {
    const s = (q || "").trim().toLowerCase()
    const lim = limit || 60
    if (!s) return LIST.slice(0, lim).map(r => ({ e: r[0], name: r[1] }))
    const out = []
    for (const r of LIST) {
        if (r[1].includes(s) || (r[2] && r[2].includes(s))) {
            out.push({ e: r[0], name: r[1] })
            if (out.length >= lim) break
        }
    }
    return out
}
